#! /bin/sh
# chkconfig: 345 95 90
# description: Open Source Flash Server
# processname: java
# Author: OPEN-ART <info@open-art.jp>
# /etc/init.d/openmeetings

. /etc/rc.d/init.d/functions

NAME=openmeetings
RED5_DIR=/usr/local/$NAME
START_DAEMON=$RED5_DIR/red5.sh
STOP_DAEMON=$RED5_DIR/red5-shutdown.sh

# OpenMeetingsを'openmeetings'ユーザ以外で稼動させる必要がある場合は、
# 次のRUN_USER変数にそのユーザIDをセットしてください。
# ex.) RUN_USER=root
RUN_USER=$NAME

PIDFILE=/var/run/$NAME.pid
LOGFILE=/var/log/$NAME.log

test -x $START_DAEMON || exit 5

start() {
    echo -n "Starting OpenMeetings Service:"
    cd $RED5_DIR
    su -s /bin/bash -c "$START_DAEMON &" $RUN_USER >> $LOGFILE 2>&1
    RETVAL=$?
    echo
    [ $RETVAL = 0 ] && touch ${PIDFILE}
    sleep 2
    return $RETVAL
}

stop() {
    echo -n "Shutting down OpenMeetings:"
    cd $RED5_DIR
    su -s /bin/bash -c "$STOP_DAEMON &" $RUN_USER >> $LOGFILE 2>&1
    RETVAL=$?
    echo
    [ $RETVAL = 0 ] && rm -f ${PIDFILE}
    sleep 2
    return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
esac